In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("creditcard_fraud_detection.csv")

In [4]:
df.shape

(284807, 31)

In [5]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [7]:
df.isnull().values.any()

np.False_

In [13]:
data = df
x = data.drop("Class", axis=1)
y = data["Class"]

In [14]:
x.isnull().values.any()

np.False_

In [15]:
y.value_counts().index

Index([0, 1], dtype='int64', name='Class')

In [17]:
y.value_counts().values

array([284315,    492])

In [2]:
# load the data into a dataframe named data
data = pd.read_csv("creditcard_fraud_detection.csv")

# seperate features (x) from target value (y)
feature = data.drop("Class", axis=1)
target = data["Class"]

In [4]:
import pandas as pd     # use pandas for handling CSV files and working with DataFrames
import matplotlib.pyplot as plt     # use matplotlib for data visualization and graphs
from sklearn.model_selection import train_test_split    # use 'train_test_split' to split arrays or matrices into random train and test subsets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE    #use SMOTE for resampling minority class
import seaborn as sns   # more data visualization

In [5]:
# create test and training subsets
feature_train, feature_test, target_train, target_test = train_test_split(
    feature, target, test_size=0.2, random_state=42
)

# train model on data BEFORE resampling with SMOTE
model = LogisticRegression(max_iter=10000)

In [6]:
# apply SMOTE to balance classes
smote = SMOTE(sampling_strategy='minority', random_state=42)
feature_train, target_train = smote.fit_resample(feature_train, target_train)  # pyright: ignore[reportAssignmentType]

In [7]:
# train logistic regression
model.fit(feature_train, target_train)

target_pred = model.predict(feature_test)

c:\Users\admin\Projects\transaction-fraud-detection\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 10000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=10000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [8]:
import numpy as np

batch_size = 10_000
probability_batches = []

for start in range(0, len(feature), batch_size):
    feature_batch = feature[start:start + batch_size]
    probability_batches.append(model.predict_proba(feature_batch))

proba = np.vstack(probability_batches)

In [9]:
# Probability of class 0
prob_class_0 = proba[:, 0]

# Probability of class 1
prob_class_1 = proba[:, 1]

# Predicted class using the default 0.5 threshold
predictions = model.classes_[np.argmax(proba, axis=1)]

In [10]:
model.classes_

array([0, 1])

In [11]:
proba[3456]

array([0.96100918, 0.03899082])

In [12]:
results = pd.DataFrame({
    "predicted_class": predictions,
    "confidence": proba.max(axis=1),
    "probability_class_1": proba[:, 1]
})